steps:
  # Pull for using cache
#- name: 'gcr.io/cloud-builders/docker'
#  args: ['pull', 'gcr.io/$PROJECT_ID/pg_sse']
  # Build
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/pg_sse:${TAG_NAME}', '.']

# Push it docker image before vulnerability scan
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/pg_sse:${TAG_NAME}']

timeout: 2400s
images: ['gcr.io/$PROJECT_ID/pg_sse:${TAG_NAME}']
